#!/usr/bin/env node
/**
 * Symmetry ratchet. Reads .symmetry-coverage.json (regenerated by
 * coverage-symmetry.mjs first) and gates two metrics:
 *   - componentsMissingStoriesCount
 *   - sourcesMissingTestsCount
 *
 * Both must NOT INCREASE relative to the baseline at .symmetry-baseline.
 * Baseline file is JSON: {"componentsMissingStories": N, "sourcesMissingTests": M}
 *
 * Usage:
 *   node scripts/symmetry-ratchet.mjs            # check
 *   node scripts/symmetry-ratchet.mjs --update   # rewrite baseline to current counts
 */
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const COVERAGE_PATH = resolve(process.cwd(), '.symmetry-coverage.json');
const BASELINE_PATH = resolve(process.cwd(), '.symmetry-baseline');
const args = process.argv.slice(2);
const updateMode = args.includes('--update');

execSync('node scripts/coverage-symmetry.mjs', { stdio: 'inherit' });

if (!existsSync(COVERAGE_PATH)) {
  console.error(`[symmetry-ratchet] missing ${COVERAGE_PATH}`);
  process.exit(2);
}

const coverage = JSON.parse(readFileSync(COVERAGE_PATH, 'utf8'));
const current = {
  componentsMissingStories: coverage.componentsMissingStoriesCount,
  sourcesMissingTests: coverage.sourcesMissingTestsCount,
};

if (updateMode) {
  writeFileSync(BASELINE_PATH, `${JSON.stringify(current, null, 2)}\n`, 'utf8');
  console.log(`[symmetry-ratchet] baseline updated to ${JSON.stringify(current)}`);
  process.exit(0);
}

if (!existsSync(BASELINE_PATH)) {
  writeFileSync(BASELINE_PATH, `${JSON.stringify(current, null, 2)}\n`, 'utf8');
  console.log(`[symmetry-ratchet] baseline file missing — initialised at ${JSON.stringify(current)}`);
  process.exit(0);
}

let baseline;
try {
  baseline = JSON.parse(readFileSync(BASELINE_PATH, 'utf8'));
} catch (err) {
  console.error(`[symmetry-ratchet] cannot parse baseline at ${BASELINE_PATH}: ${err.message}`);
  process.exit(2);
}

let regressed = false;
for (const key of ['componentsMissingStories', 'sourcesMissingTests']) {
  const c = current[key] ?? 0;
  const b = baseline[key] ?? 0;
  if (c > b) {
    console.error(`[symmetry-ratchet] FAIL: ${key} ${b} -> ${c} (+${c - b})`);
    regressed = true;
  } else if (c < b) {
    console.log(`[symmetry-ratchet] improved: ${key} ${b} -> ${c} (-${b - c})`);
  } else {
    console.log(`[symmetry-ratchet] unchanged: ${key} = ${c}`);
  }
}

if (regressed) {
  console.error('Either add the missing stories/tests or, if intentional, run: pnpm symmetry:ratchet:update');
  process.exit(1);
}

const dropped =
  current.componentsMissingStories < (baseline.componentsMissingStories ?? 0) ||
  current.sourcesMissingTests < (baseline.sourcesMissingTests ?? 0);
if (dropped) {
  console.log('Lower the baseline in the same commit: pnpm symmetry:ratchet:update');
}
process.exit(0);
